## Exercise 06.1 (selecting and passing data structures)

The task in Exercise 04 for computing the area of a triangle involved a function with six arguments ($x$ and $y$ components of each vertex). With six arguments, the likelihood of a user passing arguments in the wrong order is high. 

Use an appropriate data structure, e.g. a `list`, `tuple`, `dict`, etc,  to develop a new version of the function with a simpler interface (the interface is the arguments that are passed to the function). Add appropriate checks inside your function to validate the input data.

In [14]:
import numpy as np

def area(points):
    # check if the points list enter contains exactly three points 
    if len(points) != 3:
        print("input does not has three points")
        return
    
    # a fantastic application of list comprhension in matrix genertaion with np.
    area_matrix = np.array([[x[0], x[1], 1] for x in points])
    print(area_matrix)
    return abs(np.linalg.det(area_matrix)) / 2

points = [(0, 0), (0, 1), (1, 0)]
%time print(area(points))

[[0 0 1]
 [0 1 1]
 [1 0 1]]
0.5
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 1.69 ms


## Exercise 06.2 (selecting data structures)

For a simple (non-intersecting) polygon with $n$ vertices, $(x_0, y_0)$, $(x_1, y_1)$, . . , $(x_{n-1}, y_{n-1})$, the area $A$ is given by
$$
A = \left| \frac{1}{2} \sum_{i=0}^{n-1} \left(x_{i} y _{i+1} - x_{i+1} y_{i} \right) \right|
$$
and where $(x_n, y_n) = (x_0, y_0)$. The vertices should be ordered as you move around the polygon.

Write a function that computes the area of a simple polygon with an arbitrary number of vertices. Test your function for some simple shapes. Pay careful attention to the range of any loops.

In [23]:
def area_polygon(points):
    is_first = True
    sum = 0.0
    prev_point = ()
    for cur_point in points:
        if not is_first:
            sum += 1/2 * (prev_point[0]*cur_point[1] - prev_point[1]*cur_point[0])
        else:
            is_first = False
        prev_point = cur_point
    return abs(sum)

points = [(0, 0), (0, 1), (1, 0)]
%time print(area_polygon(points))

0.5
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 210 µs


## Exercise 06.3 (indexing)

Write a function that uses list indexing to add two vectors of arbitrary length, and returns the new vector. Include a check that the vector sizes match, and print a warning message if there is a size mismatch. The more error information you provide, the easier it would be for someone using your function to debug their code.

Add some tests of your code.

#### Hint: You can create a list of zeros of length `n` by

    z = [0]*n
    
#### Optional (advanced) 

Try writing a one-line version of this operation using list comprehension and the built-in function [`zip`](https://docs.python.org/3/library/functions.html#zip).

In [25]:
def sum_vector(x, y):
    "Return sum of two vectors"
    if len(x) != len(y):
        assert "The dimension of input vectors are different"
        return
    
    sum = []
    for i in range(len(x)):
        sum.append(x[i] + y[i])
    return sum

In [26]:
a = [0, 4.3, -5, 7]
b = [-2, 7, -15, 1]
c = sum_vector(a, b)
assert c == [-2, 11.3, -20, 8]

### Extension: list comprehension

In [47]:
def sum_vector_zip(x, y):
    "This function will sum the vectors and round to the lowest dimention of the input vectors regardlessly"
    return [a[0] + a[1] for a in zip(x, y)]

a = [0, 4.3, -5, 7]
b = [-2, 7, -15, 1]
%time c = sum_vector_zip(a, b)
c

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 15 µs


[-2, 11.3, -20, 8]

## Exercise 06.4 (dictionaries)

Create a dictionary that maps college names (the key) to college abbreviations for at least 5 colleges
(you can find abbreviations at https://en.wikipedia.org/wiki/Colleges_of_the_University_of_Cambridge#Colleges).
From the dictionary, produce and print

1. A dictionary from college abbreviation to name; and
1. A list of college abbreviations sorted into alphabetical order.

*Optional extension:* Create a dictionary that maps college names (the key) to dictionaries of:

- College abbreviation
- Year of foundation 
- Total number students
 
for at least 5 colleges. Take the data from https://en.wikipedia.org/wiki/Colleges_of_the_University_of_Cambridge#Colleges. Using this dictionary, 

1. Find the college with the greatest number of students and print the abbreviation; and 
2. Find the oldest college, and print the number of students and the abbreviation for this college.

In [54]:
abb_to_name = {}
abb_to_name["CHR"] = "Christ's"
abb_to_name["CHU"] = "Churchill"
abb_to_name["CL"] = "Clare"
abb_to_name["CLH"] = "Clare Hall"
abb_to_name["CC"] = "Corpus Christi"

abb_sorted = sorted([x for x in abb_to_name])

print(abb_to_name)
print(abb_sorted)

{'CL': 'Clare', 'CC': 'Corpus Christi', 'CLH': 'Clare Hall', 'CHU': 'Churchill', 'CHR': "Christ's"}
['CC', 'CHR', 'CHU', 'CL', 'CLH']


In [62]:
name_to_many = {}
name_to_many["Christ's"] = ("CHR", 1505, 541)
name_to_many["Churchill"] = ("CHU", 1960, 704)
name_to_many["Clare"] = ("CL", 1326, 655)
name_to_many["Clare Hall"] = ("CLH", 1966, 150)
name_to_many["Corpus Christi"] = ("CC", 1352, 467)

for x in name_to_many:
    many_dic = {}
    many_dic["College abbreviation"] = name_to_many[x][0]
    many_dic["Year of foundation"] = name_to_many[x][1]
    many_dic["Total number students"] = name_to_many[x][2]
    name_to_many[x] = many_dic

name_to_many

{"Christ's": {'College abbreviation': 'CHR',
  'Total number students': 541,
  'Year of foundation': 1505},
 'Churchill': {'College abbreviation': 'CHU',
  'Total number students': 704,
  'Year of foundation': 1960},
 'Clare': {'College abbreviation': 'CL',
  'Total number students': 655,
  'Year of foundation': 1326},
 'Clare Hall': {'College abbreviation': 'CLH',
  'Total number students': 150,
  'Year of foundation': 1966},
 'Corpus Christi': {'College abbreviation': 'CC',
  'Total number students': 467,
  'Year of foundation': 1352}}

#### Optional extension

In [68]:
max_stu = 0
max_col = "Christ's"

for col in name_to_many:
    if name_to_many[col]["Total number students"] > max_stu:
        max_col = col
        max_stu = name_to_many[col]["Total number students"]
print(name_to_many[max_col]["College abbreviation"])

old_year = 100000
old_col = "Christ's"

for col in name_to_many:
    if name_to_many[col]["Year of foundation"] < old_year:
        old_col = col
        old_year = name_to_many[col]["Year of foundation"]
print(name_to_many[old_col]["College abbreviation"], name_to_many[old_col]["Total number students"])

CHU
CL 655
